name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
        - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        - name: Install dependencies
        run: |
          npm install
           - name: Run Cypress tests
        run: |
          npx cypress run

